# permissions for end users to view locustclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: locustcluster-viewer-role
rules:
- apiGroups:
  - locust.leftbin.com
  resources:
  - locustclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - locust.leftbin.com
  resources:
  - locustclusters/status
  verbs:
  - get
