# permissions for end users to edit locustclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: locustcluster-editor-role
rules:
- apiGroups:
  - locust.leftbin.com
  resources:
  - locustclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - locust.leftbin.com
  resources:
  - locustclusters/status
  verbs:
  - get
